name: Update Badges

env:
  CREDLY_USERNAME: tiago-pomella-lobo

on: # Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  schedule:
      - cron: "0 3 * * *" # Runs at 2am UTC

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
  build: # This workflow contains a single job called "build"
    
    runs-on: ubuntu-latest # The type of runner that the job will run on
    
    permissions: 
      contents: write # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository.

    steps: # Steps represent a sequence of tasks that will be executed as part of the job
    
      - name: Branch checkout 
        uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        
      - name: Import Credly Badges (\michaelcontento)
        # uses: michaelcontento/credly-import-action@6fddb351e98b01db7407151970e0bd8b12ce27a3
        uses: michaelcontento/credly-import-action@v1.0.1 # You may pin to the exact commit or the version.
        with:
          username: tiago-pomella-lobo # Username on credly
          #datafile: # Filename where to store the JSON file (optional, default is CredlyBadges.json)
          #imagedir: # Path where to store the badge images (optional, default is CredlyBadges)
          #skip_image_downloading: # Wether or not we should download the badge images at all (optional, default is 0)
        
      - name: Update Readme with badges (\pemtajo)
        # Reference: https://pemtajo.medium.com/how-to-improve-your-github-profile-by-adding-badges-2c10363f4f9a
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: tiago-pomella-lobo # optional, but default will use the same from github
          
      - name: Commit to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Download badges and update README
